# see https://github.com/marketplace/actions/publish-markdown-as-pdf

name: Convert Markdown to PDF
on: 
  push:
    branches:
      - master
      - test
env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Document
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish Markdown As PDF
        uses: shrink/actions-document-publish@v1
        id: publish-document
        with:
          sources: 'README.md'

      - name: Commits File 
        uses: EndBug/add-and-commit@v7
        with: 
          add: ${{ steps.publish-document.outputs.pdf }}
          author_name: ${{ secrets.GH_NAME }}
          author_email: ${{ secrets.GH_EMAIL }}
          message: 'Updated pdf'
          push: true 
