# see https://github.com/marketplace/actions/publish-markdown-as-pdf

name: Convert Markdown to PDF
on: [push]
env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Document
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish Markdown As PDF
        uses: shrink/actions-document-publish@v1
        id: publish-document
        with:
          sources: 'README.md'

      - name: Save PDF
        uses: actions/upload-artifact@v2
        id: upload-document
        with:
          name: 'PDF'
          path: 'README.pdf'
