# see https://github.com/marketplace/actions/publish-markdown-as-pdf

name: Convert Markdown to PDF
on: [push]
env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Document
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish Markdown As PDF
        uses: shrink/actions-document-publish@v1
        id: publish-to-pdf
        with:
          sources: 'README.md'
      - name: Upload Document
        uses: actions/upload-artifact@v2
        id: upload-document
        with:
          name: 'README.pdf'
          path: ${{ steps.publish-document.outputs.pdf }}
